import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

/**
 * Controlled vocabularies. Adding a value here is a deliberate one-line edit;
 * an unlisted value fails the build rather than silently creating a dead filter.
 */
export const AUTONOMY = ['autonomous', 'ai-assisted', 'both', 'not-applicable'] as const;
export const MODALITY = ['text', 'voice', 'multimodal', 'not-applicable'] as const;
export const PAPER_TYPE = [
  'new-system',
  'exploratory-position',
  'evaluation-benchmark',
  'survey',
  'dataset',
] as const;
export const VENUE_TYPE = [
  'conference',
  'journal',
  'workshop',
  'preprint',
  'thesis',
  'tech-report',
] as const;

/** Fields the seed pass leaves for human judgement. Drives `npm run review`. */
export const CLASSIFICATION_FIELDS = ['autonomy', 'modality', 'paperType', 'domains'] as const;

/*
 * A bare `key:` in YAML parses as null, not undefined — so plain `.optional()` would
 * reject every field left deliberately blank. Since "leave it blank rather than guess"
 * is the whole editing convention here, optional fields must accept null and normalise
 * it away, so downstream code only ever sees a value or undefined.
 */
const blankable = <T extends z.ZodTypeAny>(schema: T) =>
  schema.nullish().transform((v) => v ?? undefined);

/** Same idea for lists: blank, missing, and [] all mean "none". */
const blankableList = <T extends z.ZodTypeAny>(schema: T) =>
  schema.nullish().transform((v) => v ?? []);

const papers = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/papers' }),
  schema: z.object({
    title: z.string(),
    authors: z.array(z.string()).min(1),

    /** Publication or preprint date. `YYYY-MM-DD`, or `YYYY-MM` for an unknown day. */
    date: z.coerce.date(),

    /** Primary link — the landing page a reader should hit first. */
    url: z.string().url(),
    arxiv: blankable(z.string()),
    doi: blankable(z.string()),
    pdfUrl: blankable(z.string().url()),

    venue: blankable(z.string()),
    venueType: z
      .enum(VENUE_TYPE)
      .nullish()
      .transform((v) => v ?? 'preprint'),

    // --- Classification: blank by design. Blank is a valid, rendered state. ---
    autonomy: blankable(z.enum(AUTONOMY)),
    modality: blankable(z.enum(MODALITY)),
    paperType: blankableList(z.array(z.enum(PAPER_TYPE))),

    /**
     * Free-text tags, lowercased and de-duplicated at load so "Health" and "health "
     * collapse. Run `npm run tags` to spot near-duplicates before they spread.
     */
    domains: blankableList(z.array(z.string())).transform((tags) =>
      [...new Set(tags.map((t: string) => t.trim().toLowerCase()).filter(Boolean))].sort(),
    ),

    code_url: blankable(z.string().url()),
    dataset_url: blankable(z.string().url()),

    /** Generated by `npm run thumbs` from the top of page 1 of the PDF. */
    thumbnail: blankable(z.string()),

    bibtex: blankable(z.string()),

    /** Field names not yet verified by a human. Surfaced by `npm run review`. */
    needsReview: blankableList(z.array(z.string())),

    /** Abstract could not be reproduced (restrictive publisher); body is our summary. */
    abstractIsSummary: z
      .boolean()
      .nullish()
      .transform((v) => v ?? false),

    draft: z
      .boolean()
      .nullish()
      .transform((v) => v ?? false),
  }),
});

export const collections = { papers };
